---
abstract: 'modify HTTP request headers'
author:
  - 'Wallace Reis C<< <wreis@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-RequestHeaders
no_index:
  directory:
    - t
    - inc
requires:
  Plack::Middleware: 0
  parent: 0
version: 0.02
